
    while (pimple.correctNonOrthogonal())
    {
       #include "0init_anode.H"
       #include "0init_cathode.H"
       #include "01solid_set.H"
       #include "OCV_anode.H"
       #include "OCV_cathode.H"
       #include "02modify_boundary_gradient.H"
       #include "03B-VEqn.H"
       #include "04fai_eSolidsEqn.H"
       #include "05fai_sSolidsEqn.H"
       #include "06CeSolidEqn.H"
       #include "07CsSolidEqn.H"
       #include "08get_results.H"
       #include "09events.H"

    }


